@extends("layouts.aqrulayout")
@section("body")


  <!-- Yield section STart here  -->


  <!-- here -->
  <main class="main" id="main">
    <div class="template-faqs-wrap">
      <section class="faqs content-container p-y-block">
        <div class="faqs__content">
          <h1 class="faqs__heading">Frequently Asked Questions</h1>
          <div class="faqs__content content-default">
            <p>Browse our most frequently asked questions, and if you can&#8217;t find what you&#8217;re looking for,
              please don&#8217;t hesitate to get in touch with the AQRU team.</p>
          </div>
          <h3 class="faqs__help-heading">Still need help?</h3>
          <div class="content-default">
            <p>Contact us below and one of our team will get back to you shortly.</p>
          </div>
          <div> <a href="mailto:help@aqru.io" class="faqs__link"> <svg xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 32 32" width="24" height="24">
                <path d="M0 0h32v32H0z" fill="none" />
                <path fill="currentColor"
                  d="M26.665 5.339H5.336a2.662 2.662 0 00-2.653 2.665L2.67 23.995a2.673 2.673 0 002.666 2.665h21.329a2.673 2.673 0 002.666-2.665V8.004a2.673 2.673 0 00-2.666-2.665zm0 5.33L16 17.332 5.336 10.669V8.004L16 14.667l10.665-6.663z" />
              </svg> <span>help@aqru.io</span> </a> </div>
        </div>
        <div class="faqs__faqs-list">
          <ul class="faqs-list ">
            <li class="faqs-list__item" data-faqs-search="what interest rates do you pay?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>What interest rates do you pay?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p>You receive up to 7% interest on USDC stablecoins, 1% on Ethereum and 1% on Bitcoin and it is all
                    yours to keep. Funds can be added and removed in cryptocurrency or fiat currency daily.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="do you charge any fees?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Do you charge any fees?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p>When you withdraw funds from the platform there is no fee for fiat withdrawals. There is a $20 for
                    crypto withdrawals, charged in the asset you are withdrawing.</p>
                  <p class="p1">What payment methods do you accept?</p>
                  <p class="p1">We accept payment by card, bank transfer, or wallet-to-wallet crypto payments (currently
                    accepting BTC, ETH, USDC)</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="how do you pay such high rates of return?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>How do you pay such high rates of return?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">AQRU generates returns by lending out our customers digital assets to institutional and
                    retail borrowers as well as participating and supporting decentralised exchanges. We have a rigorous
                    risk management process and insure deposits that we lend to decentralised exchanges.</p>
                  <p class="p1">Returns generated by cryptocurrency deposits remain high as market participants are
                    willing to pay high levels of interest to borrow assets they struggle to access via traditional
                    needs. As the crypto market develops yields will decrease as capital becomes more accessible,
                    however, we feel there will also be opportunities that emerge to generate yield to compensate.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="are you regulated?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Are you regulated?</span> <svg xmlns="http://www.w3.org/2000/svg"
                      width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p>Accru Finance Ltd. (Bulgaria) is a company registered in Bulgaria with registration number
                    206651201 whose registered address is 9 Tsarigradsko Shose, 1124, Sofia, Bulgaria. Accru Finance
                    Ltd. (Bulgaria) is a subsidiary of Accru Finance Ltd. (UK), a private limited company registered in
                    England and Wales with registration number 13133682.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="are you secure? ">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Are you secure? </span> <svg xmlns="http://www.w3.org/2000/svg"
                      width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">Cryptocurrencies are inherently high-risk products as blockchain technology is new. The
                    main risks faced by companies within the crypto space are:</p>
                  <p class="p1">Hacking – crypto wallets held by AQRU are penetrated by third parties. AQRU uses leading
                    wallet infrastructure provider Fireblocks to ensure security of assets. We also have a $30 million
                    policy in the event assets are stolen.</p>
                  <p class="p1">Coin risk – if the underlying coins are disrupted by bad actors they could lose a large
                    portion of their value. For example, if someone were to launch a 51% attack on Bitcoin, they could
                    issue large amounts of new Bitcoin thus devaluing it. We see this risk as relatively low as we only
                    provide access to the largest most liquid cryptocurrencies on our platform.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="what is the minimum deposit and withdrawal?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>What is the minimum deposit and withdrawal?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">The minimum deposit amount is $100. There isn&#8217;t a withdrawal minimum as long as
                    you can cover the fee.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="do i still own my coins when i send them to aqru?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Do I still own my coins when I send them to AQRU?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">AQRU acts as a cryptocurrency custodian. By doing so, we take full control of customer
                    assets when they are deposited. These deposits are protected by our wallet insurance provided by
                    Fireblocks.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="how long does it take to deposit or remove funds?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>How long does it take to deposit or remove funds?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">For cryptocurrency we will usually notify you of receipt of funds within 20 minutes of
                    you making a transfer.</p>
                  <p class="p1">With fiat currency, this will depend on your bank and method of payment. Some transfers
                    can take as little as an hour to be confirmed others, such as those sent internationally, can take
                    up to 5 days to clear depending on where your bank is based.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="why do i need to provide identification?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Why do I need to provide identification?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">We take all regulatory and anti-money laundering requirements extremely seriously and
                    adhere to all requirements set by regulators. We have a responsibility to ‘know our customer’ and
                    ensure we know the source of any funds transferred to an account. Please be patient with our
                    questions and document requests as these processes only strengthen the credibility and security of
                    the cryptocurrency ecosystem.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="who are aqru?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Who are AQRU?</span> <svg xmlns="http://www.w3.org/2000/svg"
                      width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">AQRU was created by an experienced team of investment, payment and technology experts.
                    AQRU was created out of a frustration with the difficulty that many people face to generate returns
                    from their cryptocurrency. The crypto market was initially created to make financial services
                    available to everyone however, it has quickly become complex, full of jargon and impenetrable to
                    everyday investors. AQRU is here to change that. We have created an easy-to-use platform making it
                    simple to convert fiat into crypto and begin earning high returns on your chosen assets immediately.
                  </p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="which cryptocurrencies do you cover?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Which cryptocurrencies do you cover?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">You can deposit or invest in Bitcoin (BTC), Ether (ETH) or stablecoins (USDC). We will
                    add more in response to demand but will always have a strict requirement that the coin have a
                    consistent track record and proven utility.</p>
                </div>
              </details>
            </li>
            <li class="faqs-list__item" data-faqs-search="do you accept corporate customers?">
              <details class="faq ">
                <summary class="faq__question__wrap">
                  <div class="faq__question"> <span>Do you accept corporate customers?</span> <svg
                      xmlns="http://www.w3.org/2000/svg" width="24.112" height="24.112" viewBox="0 0 24.112 24.112">
                      <path fill="currentColor"
                        d="M.004 9.288h9.28V.004h5.544v9.284h9.284v5.544h-9.284v9.284H9.284v-9.288H.004z" />
                    </svg> </div>
                </summary>
                <div class="faq__answer content-default">
                  <p class="p1">Yes, we do. To onboard you we will need to identify the business, directors and all
                    beneficial owners. Please email <a href="mailto:onboarding@accru.finance"><span
                        class="s1">onboarding@accru.finance</span></a> to learn more.</p>
                </div>
              </details>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </main>

  <!-- here -->


  <!-- here too -->


  <!-- main here  -->
 
 
 
  <section class="mailing-list">
    <div class="mailing-list__layout content-container">
      <div class="mailing-list__content">
        <h2 class="mailing-list__heading">Get Crypto-smart and join our mailing list.</h2>
        <div class="mailing-list__body content-default"> For the latest updates, articles, offers and earning
          opportunities, sign up today! </div>
      </div>
      <div id="mailing-list-form" class="mailing-list__form"></div>
    </div>
  </section>



    <!-- Yield section Stop here  -->

@endsection
